-- 고객 DDL

CREATE TABLE CUSTOMER 
(
  C_ID VARCHAR2(15) 
, C_PW VARCHAR2(20) 
, C_KNAME VARCHAR2(20) 
, C_ELNAME VARCHAR2(20) 
, C_EFNAME VARCHAR2(20) 
, C_SEX VARCHAR2(2) 
, C_BIRTH DATE 
, C_NATION VARCHAR2(22) 
, C_MOBILE VARCHAR2(15) 
, C_EMAIL VARCHAR2(30) 
, C_EMAILCH VARCHAR2(2) 
, C_MOBILECH VARCHAR2(2) 
, C_ADDRESS VARCHAR2(80) 
, C_GRADE VARCHAR2(10) 
, C_MILE NUMBER
, TOTALMILE NUMBER 
);


-- 직원 DDL

CREATE TABLE EMPLOYEE 
(
  E_ID NUMBER 
, E_PW VARCHAR2(20) 
, E_KNAME VARCHAR2(20) 
, E_EFNAME VARCHAR2(20) 
, E_ELNAME VARCHAR2(20) 
, E_SEX VARCHAR2(2) 
, E_BIRTH DATE 
, E_MOBILE VARCHAR2(15) 
, E_EMAIL VARCHAR2(30)
, E_ADDRESS VARCHAR2(80)
, E_STATUS VARCHAR2(2)
)

-- 비행기 DDL

CREATE TABLE AIRPLANE 
(
  A_NUM NUMBER 
, A_KIND VARCHAR2(10) 
, A_TYPE VARCHAR2(7) 
, A_PAX NUMBER 
, A_MDATE DATE 
, A_MAKE VARCHAR2(20) 
, A_STATE VARCHAR2(2) 
, A_FIRROW NUMBER 
, A_FIRCOL VARCHAR2(2) 
, A_BINROW NUMBER 
, A_BINCOL VARCHAR2(2) 
, A_ECOROW NUMBER 
, A_ECOCOL VARCHAR2(2) 
);

-- 운항일지

CREATE TABLE FLIGHT 
(
  F_DATE DATE 
, F_ANUM NUMBER 
, F_FNAME VARCHAR2(8) 
, F_LEAVE VARCHAR2(20) 
, F_LEVDATE DATE 
, F_ARRIVE VARCHAR2(20) 
, F_ARRIDATE DATE 
, F_GATE NUMBER(5) 
);

-- 예매 DDL

CREATE TABLE RESERVATION 
(
  R_NUM VARCHAR2(20)
, R_NAME VARCHAR2(40) 
, R_DEPARTURE VARCHAR2(12) 
, R_DEPARTURETIME DATE
, R_ARRIVAL VARCHAR2(12) 
, R_ARRIVALTIME DATE
, R_SEAT VARCHAR2(5) 
, R_ANUM VARCHAR2(20) 
, R_DATE DATE 
, R_FNAME VARCHAR2(20) 
, R_CLASS VARCHAR2(12) 
);

-- 표 DDL

CREATE TABLE TICKET 
(
  T_NAME VARCHAR2(40) 
, T_DATE DATE 
, T_SEAT VARCHAR2(5) 
, T_DEPARTURE VARCHAR2(12) 
, T_DEPARTURETIME DATE
, T_ARRIVAL VARCHAR2(12) 
, T_ARRIVALTIME DATE
, T_CLASS VARCHAR2(12)
, T_GATE VARCHAR2(6) 
, T_FNAME VARCHAR2(8) 
, T_BAGNUM NUMBER 
);

-- 공지사항 DDL

CREATE TABLE NOTICE 
(
  N_NUM NUMBER 
, N_TITLE VARCHAR2(40) 
, N_CONTENTS VARCHAR2(1000) 
, N_DATE DATE 
);

-- 게시판 DDL

CREATE TABLE BOARD 
(
  B_NUM NUMBER 
, B_TITLE VARCHAR2(40) 
, B_CONTENTS VARCHAR2(1000) 
, B_ID VARCHAR2(15) 
, B_DATE DATE 
, B_CHECK VARCHAR2(2) 
);

-- 게시물 번호 시퀀스
create sequence borad_seq
start with 1
increment by 1
nomaxvalue
nocycle
;

borad_seq.nextval

-- 답글 DDL

CREATE TABLE REPLY 
(
  REP_NUM NUMBER 
, REP_CONTENTS VARCHAR2(1000 BYTE) 
, REP_DATE DATE 
);


-- 도로명 DDL

CREATE TABLE POST 
(
  P_POST varchar2(6) 
, P_DO VARCHAR2(20) 
, P_GU VARCHAR2(20) 
, P_ROAD VARCHAR2(20) 
, P_RFIRST NUMBER 
, P_RSECOND NUMBER 
, P_BUILD VARCHAR2(40) 
, P_DONG VARCHAR2(20) 
, P_SUBDONG VARCHAR2(20) 
, P_DFIRST NUMBER 
, P_DSECOND NUMBER 
);